title: Ricardo Tiosso Panassiol, Ph.D.
logo: /assets/img/headshot_circle.png
description: Neuroscientist | Behavior Analyst | Brain-Machine Interface | Neuroengineering | AI and Artificial Neural Networks | R&D | Innovation
#show_downloads: true
theme: jekyll-theme-minimal
